mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "oidc123"
  max_open_conns: 200
  max_idle_conns: 50
system:
  port: 9825
wxlogin:
  h5:
    appid: "appid"
    secret: "secret"
  pc:
    appid: "appid"
    secret: "secret"
  app:
    appid: "appid"
    secret: "secret"
  mini:
    appid: "appid"
    secret: "secret"