mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "oidc"
system:
  port: 9825
wxlogin:
  h5:
    appid: "appid"
    secret: "secret"
  pc:
    appid: "appid"
    secret: "secret"
  qy_pc:
    appid: "appid"
    secret: "secret"
  app:
    appid: "appid"
    secret: "secret"
  mini:
    appid: "appid"
    secret: "secret"
dylogin:
  dy_h5:
    appid: "appid"
    secret: "secret"
  dy_pc:
    appid: "appid"
    secret: "secret"
  dy_app:
    appid: "appid"
    secret: "secret"
  dy_mini:
    appid: "appid"
    secret: "secret"