mysql:
  host: "192.168.211.213"
  port: 32045
  user: "root"
  password: "5SrWNpx5NQ"
  dbname: "oidc1"
system:
  port: 9825
wxlogin:
  h5:
    appid: "appid"
    secret: "secret"
  pc:
    appid: "appid"
    secret: "secret"
  app:
    appid: "appid"
    secret: "secret"
  mini:
    appid: "appid"
    secret: "secret"